### ISSUE TITLE
Compatibility with VTK-7.0.0

### ISSUE THREAD

**Issue by Naubertkato** [GollyGang/ready#12]
There is a minor compatibility problem with VTK-7.0.0, since vtkRenderingOpenGL (version 6.2 and above) has been replaced (apparently) by vtkRenderingOpenGL2.

Except for that, everything seems to be working correctly.

As far as I can see, the stable version of VTK-7.0 is only 4 days old, so that's not so bad, considering.

**Comment by danwills** [comment]
Nice work Tim! :D

**Comment by timhutton** [comment]
@danwills So after that I tried the simpler approach of just ${VTK_LIBRARIES} that you'd used in your Houdini branch and it seems to work everywhere so far. It break Travis but I don't see why - I can build on Ubuntu 14.04 normally.
