### ISSUE TITLE
Can't find wxWidgets (MacOS)

### ISSUE THREAD

**Issue by cthompso** [GollyGang/ready#123]
Sorry for the newbie question, but I'm having trouble building ready on Mac, as it seems make can't find my installed wxWidgets libraries:

```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)

```

I have tried setting the parameters in question to cmake, or via env variable, without success. My efforts to find a solution online have also not worked out. Does anyone know what I might be missing here? Sorry I'm new to cmake.

Colin

**Comment by timhutton** [comment]
Hello,

Which version of macOS are you on?

I assume you're following the [build instructions](https://github.com/GollyGang/ready/blob/gh-pages/BUILD.txt#L140-L178)? And wxWidgets installed OK?

As an alternative to building and installing wxWidgets you can use `brew install wxmac` I believe. (@andykt - is this right? It works on the Travis-CI build.) Maybe try that and then cmake again?

I don't use macOS but on Windows I set wxWidgets_ROOT_DIR and wxWidgets_LIB_DIR in the CMake GUI.

Tim

**Comment by cthompso** [comment]
Hi TIm-

10.14.6

Yes I followed the instructions and things built / installed correctly AFAICT.

Sadly I cannot use brew for security reasons.

I will try to see if I can set ROOT/LIB dir in the Gui. Good idea! Thank you.

Colin

(Btw, I am mostly interested in a local build since I wish to try the latest version of the Houdini HDAs. Do those not require a build of source? Does a simple git clone of the latest checkin suffice?)

**Comment by timhutton** [comment]
@cthompso @danwills can help here.

**Comment by danwills** [comment]
G'day Colin,
Tim's right there's currently no need to build Ready to use the HDA's,
they're just copied in, so you can get the latest directly from a git clone
if you want.

The  HDA(nc)'s are set up to extract info from a VTI by calling the 'rdy'
command from a build (there's a "Ready Install Path" parameter), but there
is no binary linkage or dependency.

They also do not rely on (or indeed yet support) any of the new keywords
features so the rdy from the previous build should work (it mostly works
with formula mode VTIs). That's cool though should hopefully still be
possible to load quite a few that come with Ready that only use Laplacian.

Feel free to email me directly (gdanzo@gmail.com) if you need a hand
getting it working. Cheers for giving it a try too!

Dan

**Comment by cthompso** [comment]
Awesome thanks gents! I will pull from the latest and see how it goes!

much appreciated,

colin

**Comment by timhutton** [comment]
@cthompso Please reopen this issue if you are still having problems.
