### ISSUE TITLE
LINK error: cannot open file 'vtkRenderingFreeTypeOpenGL.lib'

### ISSUE THREAD

**Issue by chenweikai** [GollyGang/ready#13]
Hi Tim

I was trying to build Ready. Wx + VTK were compiled fine. However, I received the following error:

LINK : fatal error LNK1104: cannot open file 'vtkRenderingFreeTypeOpenGL.lib'

It seems that the RenderingFreeTypeOpenGL module no longer exists in latest vtk. Any way to remove this error?

By the way, I'm using VTK7.0 + Wx 3.0.2 under Win10 + VS2013.

Thanks!

**Comment by timhutton** [comment]
Same issue as #12. For now use an older VTK.

**Comment by chenweikai** [comment]
Noted. Thanks!
