### ISSUE TITLE
OpenCL errors in Ubuntu Mate 20.04.1

### ISSUE THREAD

**Issue by ghost** [GollyGang/ready#131]
This is odd, all the non-CPU scripts in Ready stopped working after doing an autoremove at one point. It just gives the following error:

Failed to open file. Error:

OpenCLImageRD::ReloadKernelIfNeeded : build failed (kernel saved as kernel.txt):

Invalid build options

This is strange since the same build worked with non-CPU scripts before. Does anyone know what I'm supposed to install so that it works? 

I'm using an AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx × 4 

My binaries are attached, can anyone test this on a different device and see if it works?

[ApollyonReady.zip](https://github.com/GollyGang/ready/files/5861537/ApollyonReady.zip)

**Comment by timhutton** [comment]
Did you try reinstalling the required packages:

`sudo apt-get install libgtk-3-dev libxt-dev ocl-icd-opencl-dev libglu1-mesa-dev libvtk7-dev libwxgtk3.0-gtk3-dev cmake-curses-gui build-essential git libboost-all-dev`

**Comment by ghost** [comment]
Yep, no luck.

**Comment by timhutton** [comment]
You could look through the autoremove log and work out what the package was, or reinstall everything. I've been burnt by autoremove before.

It is likely something in OpenCL that is broken, as the error is in trying to compile the OpenCL kernel. You could try to completely uninstall and reinstall `ocl-icd-opencl-dev`.

Otherwise, is it time to upgrade your distro?

**Comment by timhutton** [comment]
@Apollyon094 Please reopen this issue if you are still having problems.

**Comment by ghost** [comment]
Could I have a linux build? I'd like to see if it works.

**Comment by timhutton** [comment]
[Ready-0.11.0-Linux-64bit.zip](https://github.com/GollyGang/ready/files/5920327/Ready-0.11.0-Linux-64bit.zip)
Ubuntu 20.04

Let me know how you get on.
