### ISSUE TITLE
Cannot open any files - Windows

### ISSUE THREAD

**Issue by vicsjoo** [GollyGang/ready#152]
When I launch the program, and try to open any .vti file it shows the message: 

> Failed to open file. Error:
> Unsupported data type or file read error

The same as issue  #19 , this on Windows. Downloaded the last build from github.

**Comment by timhutton** [comment]
Hi @vicsjoo. Are there non-ASCII characters on the path?

**Comment by vicsjoo** [comment]
> Hi @vicsjoo. Are there non-ASCII characters on the path?

Yes, my user folder. After reading your reply I moved it to C:\ path, now it works fine. I'm closing the issue.

**Comment by timhutton** [comment]
Thanks for updating. Sorry you hit this bug.

**Comment by timhutton** [comment]
Same as #59
