### ISSUE TITLE
Build instructions for debian 12 (bookworm)

### ISSUE THREAD

**Issue by Goutte** [GollyGang/ready#166]
Instead of `libwxgtk3.0-gtk3-dev`, install `libwxgtk3.2-dev` :

    apt install libwxgtk3.2-dev

When `cmake` fails with :

```
CMake Error at CMakeLists.txt:460 (message):
  Didn't find -lwx_gtk2u_core-3.0 or -lwx_gtk3u_core-3.0 in
  wxWidgets_LIBRARIES - unable to detect GTK version to use:
  -L/usr/lib/x86_64-linux-gnu;-pthread;;;-lwx_gtk3u_html-3.2;-lwx_gtk3u_aui-3.2;-lwx_gtk3u_gl-3.2;-lwx_gtk3u_core-3.2;-lwx_baseu-3.2
```

Open `CMakeLists.txt` and replace `-lwx_gtk3u_core-3.0` by `lwx_gtk3u_core-3.2` in :

    elseif("-lwx_gtk3u_core-3.0" IN_LIST wxWidgets_LIBRARIES)

Then it'll build and run fine, except for some dark theme issues that may or may not be caused by this replacement.

I could not figure out how to configure cmake to fix this properly for everyone (grepped for `wx_gtk3u_core`, nothing), but at least I can leave these breadcrumbs.

Thanks for the great software, I'm experimenting with the [Sisyphus automaton](https://conwaylife.com/forums/viewtopic.php?f=11&t=6561).

**Comment by timhutton** [comment]
Thanks for reporting. Looks like similar issues on ubuntu-24.04.

**Comment by timhutton** [comment]
Working on #167 to resolve this issue.
