### ISSUE TITLE
Can't open OpenCL patterns

### ISSUE THREAD

**Issue by kynjo** [GollyGang/ready#18]
![2017-11-14 22-57-48](https://user-images.githubusercontent.com/33669932/32803075-75b01772-c993-11e7-906b-8e95c8385647.png)

OpenCL_MixIn::ReloadContextIfNeeded : Failed to create context: Unknown

I select OpenCLDevice. Try started win build on wine - but not found OpenCL. 
LinuxMint 18.2 sonya
x86_64 Linux 4.10.0-33-generic
GeForce GT 640
CPU - all Ok

**Comment by timhutton** [comment]
@kynjo Could you post the results of `Action > Show OpenCL diagnostics...`?

**Comment by kynjo** [comment]
Found 1 platform(s):
Platform 1:
CL_PLATFORM_PROFILE : FULL_PROFILE
CL_PLATFORM_VERSION : OpenCL 1.2 CUDA 9.0.194
CL_PLATFORM_NAME : NVIDIA CUDA
CL_PLATFORM_VENDOR : NVIDIA Corporation
CL_PLATFORM_EXTENSIONS : cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer

Found 1 device(s) on this platform.
Device 1:
CL_DEVICE_EXTENSIONS : cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
CL_DEVICE_NAME : GeForce GT 640
CL_DEVICE_PROFILE : FULL_PROFILE
CL_DEVICE_VENDOR : NVIDIA Corporation
CL_DEVICE_VERSION : OpenCL 1.2 CUDA
CL_DRIVER_VERSION : 384.90
CL_DEVICE_ADDRESS_BITS : 64
CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE : 128
CL_DEVICE_MAX_CLOCK_FREQUENCY : 901
CL_DEVICE_MAX_COMPUTE_UNITS : 2
CL_DEVICE_MAX_CONSTANT_ARGS : 9
CL_DEVICE_MAX_READ_IMAGE_ARGS : 256
CL_DEVICE_MAX_SAMPLERS : 32
CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS : 3
CL_DEVICE_MAX_WRITE_IMAGE_ARGS : 16
CL_DEVICE_MEM_BASE_ADDR_ALIGN : 4096
CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE : 128
CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT : 1
CL_DEVICE_VENDOR_ID : 4318
CL_DEVICE_AVAILABLE : yes
CL_DEVICE_COMPILER_AVAILABLE : yes
CL_DEVICE_ENDIAN_LITTLE : yes
CL_DEVICE_ERROR_CORRECTION_SUPPORT : no
CL_DEVICE_IMAGE_SUPPORT : yes
CL_DEVICE_GLOBAL_MEM_CACHE_SIZE : 32768
CL_DEVICE_GLOBAL_MEM_SIZE : 2087911424
CL_DEVICE_LOCAL_MEM_SIZE : 49152
CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE : 65536
CL_DEVICE_MAX_MEM_ALLOC_SIZE : 521977856
CL_DEVICE_IMAGE2D_MAX_HEIGHT : 16384
CL_DEVICE_IMAGE2D_MAX_WIDTH : 16384
CL_DEVICE_IMAGE3D_MAX_DEPTH : 4096
CL_DEVICE_IMAGE3D_MAX_HEIGHT : 4096
CL_DEVICE_IMAGE3D_MAX_WIDTH : 4096
CL_DEVICE_MAX_PARAMETER_SIZE : 4352
CL_DEVICE_MAX_WORK_GROUP_SIZE : 1024
CL_DEVICE_PROFILING_TIMER_RESOLUTION : 1000
CL_DEVICE_SINGLE_FP_CONFIG : CL_FP_DENORM CL_FP_INF_NAN CL_FP_ROUND_TO_NEAREST CL_FP_ROUND_TO_ZERO CL_FP_ROUND_TO_INF CL_FP_FMA
CL_DEVICE_DOUBLE_FP_CONFIG : CL_FP_DENORM CL_FP_INF_NAN CL_FP_ROUND_TO_NEAREST CL_FP_ROUND_TO_ZERO CL_FP_ROUND_TO_INF CL_FP_FMA
CL_DEVICE_MAX_WORK_ITEM_SIZES : 1024, 1024, 64
CL_DEVICE_TYPE : GPU

**Comment by bobikoff** [comment]
![scrnshot_ready_01](https://user-images.githubusercontent.com/52065292/59919889-5f054500-9431-11e9-887a-af0f54b7f87a.jpg)

Found 1 platform(s):
Platform 1:
CL_PLATFORM_PROFILE : FULL_PROFILE
CL_PLATFORM_VERSION : OpenCL 2.0 AMD-APP (2482.3)
CL_PLATFORM_NAME : AMD Accelerated Parallel Processing
CL_PLATFORM_VENDOR : Advanced Micro Devices, Inc.
CL_PLATFORM_EXTENSIONS : cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
Found 1 device(s) on this platform.
Device 1:
CL_DEVICE_EXTENSIONS : cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event 
CL_DEVICE_NAME : Oland
CL_DEVICE_PROFILE : FULL_PROFILE
CL_DEVICE_VENDOR : Advanced Micro Devices, Inc.
CL_DEVICE_VERSION : OpenCL 1.2 AMD-APP (2482.3)
CL_DRIVER_VERSION : 2482.3
CL_DEVICE_ADDRESS_BITS : 32
CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE : 64
CL_DEVICE_MAX_CLOCK_FREQUENCY : 780
CL_DEVICE_MAX_COMPUTE_UNITS : 5
CL_DEVICE_MAX_CONSTANT_ARGS : 8
CL_DEVICE_MAX_READ_IMAGE_ARGS : 128
CL_DEVICE_MAX_SAMPLERS : 16
CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS : 3
CL_DEVICE_MAX_WRITE_IMAGE_ARGS : 8
CL_DEVICE_MEM_BASE_ADDR_ALIGN : 2048
CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE : 128
CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT : 1
CL_DEVICE_VENDOR_ID : 4098
CL_DEVICE_AVAILABLE : yes
CL_DEVICE_COMPILER_AVAILABLE : yes
CL_DEVICE_ENDIAN_LITTLE : yes
CL_DEVICE_ERROR_CORRECTION_SUPPORT : no
CL_DEVICE_IMAGE_SUPPORT : yes
CL_DEVICE_GLOBAL_MEM_CACHE_SIZE : 16384
CL_DEVICE_GLOBAL_MEM_SIZE : 975572992
CL_DEVICE_LOCAL_MEM_SIZE : 32768
CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE : 65536
CL_DEVICE_MAX_MEM_ALLOC_SIZE : 622774681
CL_DEVICE_IMAGE2D_MAX_HEIGHT : 16384
CL_DEVICE_IMAGE2D_MAX_WIDTH : 16384
CL_DEVICE_IMAGE3D_MAX_DEPTH : 2048
CL_DEVICE_IMAGE3D_MAX_HEIGHT : 2048
CL_DEVICE_IMAGE3D_MAX_WIDTH : 2048
CL_DEVICE_MAX_PARAMETER_SIZE : 1024
CL_DEVICE_MAX_WORK_GROUP_SIZE : 256
CL_DEVICE_PROFILING_TIMER_RESOLUTION : 1
CL_DEVICE_SINGLE_FP_CONFIG : CL_FP_INF_NAN CL_FP_ROUND_TO_NEAREST CL_FP_ROUND_TO_ZERO CL_FP_ROUND_TO_INF CL_FP_FMA
CL_DEVICE_DOUBLE_FP_CONFIG : CL_FP_DENORM CL_FP_INF_NAN CL_FP_ROUND_TO_NEAREST CL_FP_ROUND_TO_ZERO CL_FP_ROUND_TO_INF CL_FP_FMA
CL_DEVICE_MAX_WORK_ITEM_SIZES : 256, 256, 256
CL_DEVICE_TYPE : GPU

Failed to open file. Error:
OpenCL_MixIn::ReloadContextIfNeeded : Failed to create command queue: Out of host memory

Same problem in 0.7 and 0.8 versions.
Ubuntu 16.04
In Ubuntu 14 everything worked OK.

**Comment by bobikoff** [comment]
Upgrated Ubuntu to 18.
rebuild.
same problem.

> j250619@j250619c:~/programs/Ready/build$ ./rdy -v -n 2 -i ./Patterns/wave_equation.vti 
>Verbose was enabled.>
>Num Iterations was set to: 2.
>VTI-in flag detected!
>OpenCL found.
>Loading VTI file: ./Patterns/wave_equation.vti...
>Error creating system!:
>OpenCL_MixIn::ReloadContextIfNeeded : Failed to create command queue: Out of host memory
>Ignoring exception.
>Run the simulation for 2 steps...
>Segmentation fault (core dumped)

Found 1 platform(s):
Platform 1:
CL_PLATFORM_PROFILE : FULL_PROFILE
CL_PLATFORM_VERSION : OpenCL 2.1 AMD-APP (2841.17)
CL_PLATFORM_NAME : AMD Accelerated Parallel Processing
CL_PLATFORM_VENDOR : Advanced Micro Devices, Inc.
CL_PLATFORM_EXTENSIONS : cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 

Found 1 device(s) on this platform.
Device 1:
CL_DEVICE_EXTENSIONS : cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event 
CL_DEVICE_NAME : Oland
CL_DEVICE_PROFILE : FULL_PROFILE
CL_DEVICE_VENDOR : Advanced Micro Devices, Inc.
CL_DEVICE_VERSION : OpenCL 1.2 AMD-APP (2841.17)
CL_DRIVER_VERSION : 2841.17
CL_DEVICE_ADDRESS_BITS : 32
CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE : 64
CL_DEVICE_MAX_CLOCK_FREQUENCY : 780
CL_DEVICE_MAX_COMPUTE_UNITS : 5
CL_DEVICE_MAX_CONSTANT_ARGS : 8
CL_DEVICE_MAX_READ_IMAGE_ARGS : 128
CL_DEVICE_MAX_SAMPLERS : 16
CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS : 3
CL_DEVICE_MAX_WRITE_IMAGE_ARGS : 8
CL_DEVICE_MEM_BASE_ADDR_ALIGN : 2048
CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE : 128
CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT : 1
CL_DEVICE_VENDOR_ID : 4098
CL_DEVICE_AVAILABLE : yes
CL_DEVICE_COMPILER_AVAILABLE : yes
CL_DEVICE_ENDIAN_LITTLE : yes
CL_DEVICE_ERROR_CORRECTION_SUPPORT : no
CL_DEVICE_IMAGE_SUPPORT : yes
CL_DEVICE_GLOBAL_MEM_CACHE_SIZE : 16384
CL_DEVICE_GLOBAL_MEM_SIZE : 830840832
CL_DEVICE_LOCAL_MEM_SIZE : 32768
CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE : 65536
CL_DEVICE_MAX_MEM_ALLOC_SIZE : 544222822
CL_DEVICE_IMAGE2D_MAX_HEIGHT : 16384
CL_DEVICE_IMAGE2D_MAX_WIDTH : 16384
CL_DEVICE_IMAGE3D_MAX_DEPTH : 2048
CL_DEVICE_IMAGE3D_MAX_HEIGHT : 2048
CL_DEVICE_IMAGE3D_MAX_WIDTH : 2048
CL_DEVICE_MAX_PARAMETER_SIZE : 1024
CL_DEVICE_MAX_WORK_GROUP_SIZE : 256
CL_DEVICE_PROFILING_TIMER_RESOLUTION : 1
CL_DEVICE_SINGLE_FP_CONFIG : CL_FP_INF_NAN CL_FP_ROUND_TO_NEAREST CL_FP_ROUND_TO_ZERO CL_FP_ROUND_TO_INF CL_FP_FMA
CL_DEVICE_DOUBLE_FP_CONFIG : CL_FP_DENORM CL_FP_INF_NAN CL_FP_ROUND_TO_NEAREST CL_FP_ROUND_TO_ZERO CL_FP_ROUND_TO_INF CL_FP_FMA
CL_DEVICE_MAX_WORK_ITEM_SIZES : 1024, 1024, 1024
CL_DEVICE_TYPE : GPU

**Comment by timhutton** [comment]
Closing this because of the time elapsed. Sorry we didn't have any suggestions. :(
