### ISSUE TITLE
Cannot open any files

### ISSUE THREAD

**Issue by ybabel** [GollyGang/ready#19]
I'm on Ubuntu 17.10. Whatever file I try to open I get :

> Failed to open file. Error:
> 
> Unsupported data type or file read error
![ready-error](https://user-images.githubusercontent.com/1323282/33578299-647ff130-d946-11e7-99d8-ae566e44a56b.png)

I have no OpenCL device but the starting page is a 3D gray-scott model fully functionnal. It doesn't seem to be the cause of my error.
Tried with 0.7 and 0.8, same error.
The files are accessible with gedit.

**Comment by ybabel** [comment]
I get the same error with "CPU only" patterns. I get the same error running with sudo.

**Comment by ybabel** [comment]
I build from the last sources : no problem any more.

**Comment by vicsjoo** [comment]
I am having the exact same issue on Windows now :(
