### ISSUE TITLE
File>Import Image> ---- not working on Mac version?

### ISSUE THREAD

**Issue by sehablacaveman** [GollyGang/ready#20]
I'm having difficulty getting an image to import as a chemical mask on the Mac version of Ready.  I've tried various combinations of .PNG, .JPG and .BMP, but haven't had any success.  Any recommendations, or is this a known bug?

**Comment by timhutton** [comment]
Hi @sehablacaveman. We do seem to be having trouble importing images, on all platforms. We need to fix this.

I can get it to work sometimes with this image:
![image](https://user-images.githubusercontent.com/647092/36025032-9437c5a2-0d89-11e8-9610-60ac6f0f189c.png)
(save to a png)

By doing the following:
1. open parameter_modulation_demo.vti
2. File > Import Image...
3. Select the pengiun image file
4. Set 'Apply to chemical' to 'c'
5. Hit OK.

With the result looking like this:
![image](https://user-images.githubusercontent.com/647092/36025166-01e1143c-0d8a-11e8-8b9e-a2568b78384e.png)
(Which is upside down but at least it arrived.)

But intermittently it doesn't work. Restarting Ready seems to help.

**Comment by timhutton** [comment]
This is now fixed.

**Comment by danwills** [comment]
Nice work Tim!
