### ISSUE TITLE
Import Image results in random solid values (Win7, 64bit)

### ISSUE THREAD

**Issue by torridgristle** [GollyGang/ready#38]
Importing any image, seemingly no matter the format, sets the target chemical to one solid value. I'm not sure if there's an actual pattern to the resulting value because importing a 256x256 color PNG of solid black into Lesmes_noisty.vti at 256x256x1 turns the target chemical into 0.705882, and importing it again sets it to 0.0470588, and importing it again sets it to 0.188235, etc. They all seem to be integers divided 255, like 180, 12, and 48, but I don't see these values in my PNG file anywhere (B4, 0C, and 30).

Importing a file of 256 00 bytes with the PNG filename extension results in solid values as well, Not getting any errors about it not being a legit PNG, it only gave me an error when it had RAW as the filename extension. 0.027451 and 0.0392157 and 0.054902 and 0.0156863, or 7 and 10 and 14 and 4. So it probably has nothing to do with the file contents at all, either as the raw data or as a decoded bitmap.

Tested on Windows 7 64bit, Ready 0.8 64bit

**Comment by timhutton** [comment]
Thansk for reporting this @torridgristle

The fix will be in Ready 0.9
