### ISSUE TITLE
Minor: Split normals where contour hits boundary

### ISSUE THREAD

**Issue by timhutton** [GollyGang/ready#47]
The current contour surface has been given averaged normals everywhere, giving strange rendering effects like the black ring visible here on the right:
![image](https://user-images.githubusercontent.com/647092/71001183-a284f700-20d4-11ea-95e3-0bd67b359e1c.png)
We don't want to allow the automatic splitting that comes with vtkPolyDataNormals which would sometimes give creases inside our surfaces. But we do want split normals on the boundary, always.

Source code where the capping happens: [readybase/ImageRD.cpp L888](https://github.com/GollyGang/ready/blob/gh-pages/src/readybase/ImageRD.cpp#L888-L908)

**Comment by timhutton** [comment]
Now looks much better:
![image](https://user-images.githubusercontent.com/647092/72092502-53fcfe00-330a-11ea-8941-c3af6ae20913.png)

**Comment by danwills** [comment]
Awesome work fixing that Tim! It looks so much better now, great improvement! :D
