### ISSUE TITLE
Running rdy with no arguments gives scary error message

### ISSUE THREAD

**Issue by timhutton** [GollyGang/ready#56]
```
It looks like one of the required arguments is missing or malformed:
the option '--vti-in' is required but missing

Here's the help:
Error creating system!:
Unsupported data type or file read error
Ignoring exception.
```

It would be better to just print out the usage here instead of trying to do something.

**Comment by danwills** [comment]
Whoops! It was meant to just print the help and exit.

I committed and pushed a fix (it now prints the help and exits).

The numbers that the git push command printed are:
0002948..b9baf5f
Apologies I'm not sure if these are the right numbers! - still working out how to operate github properly/well.

I'll wait till you've had a look at the fix Tim, and then we could close this?

**Comment by danwills** [comment]
Blargh! I need to use a better editor, my fix was badly formatted because of tabs.. all converted to spaces in this push:
b9baf5f..65c2bf4

**Comment by timhutton** [comment]
Thanks Dan!
