### ISSUE TITLE
Windows build problem

### ISSUE THREAD

**Issue by xibxor** [GollyGang/ready#6]
So I just went through the arduous process of installing cmake, compiling vtk, wxwidgets, etc. It's not easy to build ready, but I'm sure it's worth it :-)

Ran into a problem where when building windows-Release-x64 of ready, I get many "error C3861: 'max': identifier not found" all over readybase

The error was because max is used without including "minmax.h" on windows. 

This can be fixed by including minmax.h conditionally for windows, or instead using std::max and std::min which is platform independent. I can create a commit/pull request for either solution, just let me know what's preferred.

**Comment by danwills** [comment]
Not my call, but I'd lean towards the platform independant
std::max/std::min option, at least that would reduce the complexity of the
build by a tiny sliver.

Thanks for offering to help! :D
Dan

**Comment by timhutton** [comment]
This is fixed now.
