### ISSUE TITLE
Provide bilaplacian, x_gradient, etc. when needed

### ISSUE THREAD

**Issue by timhutton** [GollyGang/ready#87]
This would allow more rules to be formula rules rather than full kernels.

Scan the formula for reserved keywords (laplacian_a, bilaplacian_b, x_gradient_a, etc.) and provide the ones that are used.

**Comment by danwills** [comment]
Great plan! Would be really cool if it only computed each 'built-in' component if they were used in the formula, then we could add all sorts of things like curl/divergence, various gradients, complex number operations, convolutions, all sorts of possibilities
