### ISSUE TITLE
Pattern requires OpenCL

### ISSUE THREAD

**Issue by lemoniada** [GollyGang/ready#9]
Hello,

I can't open any patter because of this error: "Failed to open file. Error: Pattern requires OpenCL". I have pretty old computer: intel core 2 duo, windows 7 32-bit, Mobile Intel® 4 Series Express Chipset Family. I don't know how to install openCL. Can you help me?

**Comment by timhutton** [comment]
Suggestion here is to try the AMD SDK:
http://stackoverflow.com/questions/16647567/opencl-sdk-for-intel-core-2-due
Let me know if this works for you.

Tim

**Comment by lemoniada** [comment]
It works! Thank you so much! :+1:

**Comment by timhutton** [comment]
Great, thanks for letting me know.

Will close this issue when Ready gives a better error message, with links to the possible SDKs that could be installed.
